---
title: "Learning to reference figures, tables and sections"
author: "Fan"
date: "21/03/2021"
output:
  bookdown::html_document2
keep_md: true
---

```{r global, include=FALSE}
knitr::opts_chunk$set(fig.align ="center")
```

```{r , message=FALSE}
library(tidyverse)
```

# Learning to reference figures

```{r Figref, fig.cap="This is random noise."}
x = seq(1:100)
y = rnorm(100)
dat = data.frame(x, y)
ggplot(dat, aes(x = x, y = y)) +
  geom_line()
```

This is to reference Figure \@ref(fig:Figref).

# Learning to reference tables

```{r Tabref}
dat[1:5,] %>% 
  knitr::kable(caption = "A table of the first 5 rows.")
```

This is to reference Table \@ref(tab:Tabref).

```{r}
library(COVID19)
```

# Exploring the expansion of COVID19

```{r COVIDcases, cache=TRUE}
COVID_AU <- world("country") %>%
  dplyr::filter(country == "Australia") %>%
  droplevels()
p1 = ggplot(COVID_AU, aes(x = date, y = confirmed)) +
  geom_line()
p1
```
This is to reference the COVID19 figure \@ref(fig:COVIDcases). 

